import Header from "@/components/global/Header";
import MainSection from "@/components/homePage/MainSection";
import ProductCard from "@/components/searchPage/ProductCard";
import Layout from "@/layout/Layout";
import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Scraptical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <MainSection />
      </Layout>
    </>
  );
};

export default Home;
